name: Continuous Integration

on:
  # Trigger on pull requests to development branch
  pull_request:
    branches:
      - development

  # Trigger on pushes to development branch (excluding linting)
  push:
    branches:
      - development
    paths-ignore:
      - '**/*.yml'
      - '**/README.md'

jobs:
  # Test job (including linting)
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r backend-flask/requirements.txt

      - name: Run Python linting (flake8)
        run: flake8 backend-flask/**/*.py
        if: github.event_name == 'pull_request'

      - name: Run Python type checking (mypy)
        run: mypy backend-flask/**/*.py
        if: github.event_name == 'pull_request'

      - name: Run Python unit tests
        run: python -m unittest discover backend-flask