name: Continuous Integration

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install -r backend-flask/requirements.txt

      - name: Run Python linting
        run: pycodestyle ./backend-flask/*.py

      - name: Run Python type checking
        run: mypy ./backend-flask/*.py

      - name: Run Python unittests
        run: python -m unittest discover backend-flask
