name: Continuous Integration

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r backend-flask/requirements.txt

      - name: Run Python linting
        run: |  
          flake8 $(find ./backend-flask -name "*.py")

      - name: Run Python type checking
        run: mypy $(find ./backend-flask -name "*.py")

      - name: Run Python unit tests
        run: python -m unittest discover backend-flask
